### ISSUE TITLE
Open json file as json object in Python?

### ISSUE THREAD

**Issue by pigcake999** [iplo/Specter#1]
# Help Needed
if you would like to share the answer that would be greatly appreciated.

Or if you would like to join iplo just ask.

**Comment by WAUthethird** [comment]
You might want to find a converter... There are probably converters online. Or you could use Dreamweaver.

**Comment by pigcake999** [comment]
Yeh I found a different way to do it
btw check out https://github.com/pigcake999yt/Py2Bin
